### ISSUE TITLE
Make www repo public

### ISSUE THREAD

**Issue by planetf1** [open-quantum-safe/tsc#20]
I was looking for the source of the openquantumsafe website, but was unable to find it.

Currently https://github.com/open-quantum-safe/www appears to be private. (I'm not a project member currently I expect)

Can I suggest this is made public, as I expect we would want to encourage contributions

**Comment by dstebila** [comment]
> I was looking for the source of the openquantumsafe website, but was unable to find it.
> 
> Currently https://github.com/open-quantum-safe/www appears to be private. (I'm not a project member currently I expect)
> 
> Can I suggest this is made public, as I expect we would want to encourage contributions

Done.

**Comment by planetf1** [comment]
I'm not able to see the repo - is it definitely public now?
```shell
gh repo list open-quantum-safe --json name -q '.[].name'
oqs-provider
tsc
liboqs
oqs-demos
liboqs-go
liboqs-cpp
liboqs-python
liboqs-rust
ci-containers
boringssl
.github
liboqs-dotnet
liboqs-java
libssh
openssh
openssl
profiling
oqs-engine
```

**Comment by dstebila** [comment]
> I'm not able to see the repo - is it definitely public now?

I thought I had done it, but it was still marked private. I've changed it today -- try now.

**Comment by SWilson4** [comment]
For what it's worth, the www repo still appears to be private.

**Comment by dstebila** [comment]
> For what it's worth, the www repo still appears to be private.

I don't know what's going on.  Indeed when I looked just now it said private. I've clicked the "Make public" button yet again and at least at this moment it is public.

<img width="1430" alt="Screenshot 2024-04-24 at 5 23 55 PM" src="https://github.com/open-quantum-safe/tsc/assets/8843219/44328582-92f8-49f0-9cc6-14ec6af2f77a">

**Comment by planetf1** [comment]
I realise now.. It's the automated permissions update

The visibility is set to private at https://github.com/open-quantum-safe/tsc/blob/d9675e51adc2b66265bbae464f4504f9027c8af6/config.yaml#L140

Proposed PR #21 to fix
